version: '3'
services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app:delegated
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
